version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
    command: npm start

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"