version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=mongodb+srv://rohitgcsers:jaimyoaVqwN7Ivdb@inventory.t71blw9.mongodb.net/landslide_inventory?retryWrites=true&w=majority
    depends_on:
      - redis
    command: npm start

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"